[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.6"

[functions]
  directory = "netlify/functions"

# Prevent secrets scanning from failing the build
[build.processing]
  skip_processing = true

[build.processing.html]
  pretty_urls = true

# Configure secrets scanning
[secrets]
  SECRETS_SCAN_OMIT_PATHS = ["dist/assets/*"]

# SPA redirect rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.supabase.co https://*.supabase.in https://accounts.google.com https://js.stripe.com https://m.stripe.network https://cdn.jsdelivr.net https://unpkg.com https://*.hcaptcha.com https://hcaptcha.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://js.stripe.com;
      img-src 'self' data: https: blob: https://q.stripe.com https://*.stripe.com https://*.supabase.co https://q.stripe.com https://qr.stripe.com https://b.stripecdn.com https://files.stripe.com https://stripe-camo.global.ssl.fastly.net https://d1wqzb5bdbcre6.cloudfront.net https://m.stripe.network https://m.stripe.com;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.supabase.in https://api.stripe.com https://js.stripe.com https://api.openai.com https://*.hcaptcha.com https://api.hcaptcha.com;
      frame-src 'self' https://*.stripe.com https://js.stripe.com https://*.hcaptcha.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      upgrade-insecure-requests;
      block-all-mixed-content;
    """
